index:
    path: /
    controller: App\Controller\RickMorty\GetApiController::getData

characters:
    path: /characters
    controller: App\Controller\RickMorty\GetCharactersController::getData

questions:
    path: /questions
    controller: App\Controller\Trivia\GetQuestionsController::getQuestions

question/{id}:
    path: /question/{id}
    controller: App\Controller\Trivia\GetQuestionController::getQuestion
